FROM golang:1.17 AS builder

# Magic line, notice in use that the lib name is different!
RUN apt-get update && apt-get install -y gcc-aarch64-linux-gnu

ENV GO111MODULE=off \
    CGO_ENABLED=1 \
    GOOS=linux \
    GOARCH=arm64 \
    CC=aarch64-linux-gnu-gcc

# Add your app and do what you need to for dependencies
WORKDIR /build
COPY ./app.go .

RUN go build -o app ./app.go

# Final stage - pick any old arm64 image you want
FROM multiarch/ubuntu-core:arm64-bionic
WORKDIR /root/
EXPOSE 8080
COPY --from=builder /build/app .
CMD ["./app"]