---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-arm64
  labels:
    app: python-arm64
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-arm64
  template:
    metadata:
      labels:
        app: python-arm64
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64
      containers:
      - name: python
        image: public.ecr.aws/v1d1a0v9/flask-simple:latest
        ports:
        - containerPort: 80
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: python-arm64
spec:
  type: NodePort
  selector:
    app: python-arm64
  ports:
    - port: 80