#public.ecr.aws/v4f3f9r2/krol/go_api_simple:v0.5.0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-x86
  labels:
    app: go-x86
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-x86
  template:
    metadata:
      labels:
        app: go-x86
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
      - name: go
        image: 164382793440.dkr.ecr.us-west-2.amazonaws.com/reinvent/app3:x86
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: go-x86
spec:
  type: NodePort
  selector:
    app: go-x86
  ports:
    - port: 80