---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-arm64
  labels:
    app: go-arm64
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-arm64
  template:
    metadata:
      labels:
        app: go-arm64
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64
      containers:
      - name: go
        image: 164382793440.dkr.ecr.us-west-2.amazonaws.com/reinvent/app3:arm64
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: go-arm64
spec:
  type: NodePort
  selector:
    app: go-arm64
  ports:
    - port: 80